// English translations
const en: Record<string, string> = {
  // === Navigation (Sidebar) ===
  "nav.home": "Home",
  "nav.feed": "Feed",
  "nav.generator": "Generator",
  "nav.templates": "Templates",
  "nav.marketplace": "Marketplace",
  "nav.gallery": "Gallery",
  "nav.myGenerations": "My Generations",
  "nav.myTemplates": "My Templates",
  "nav.aiProviders": "AI Providers",
  "nav.cloud": "Cloud",
  "nav.profile": "Profile",
  "nav.billing": "Billing & Plans",
  "nav.sectionOverview": "Overview",
  "nav.sectionStudio": "Studio",
  "nav.sectionSettings": "Settings",
  "nav.adminPanel": "Admin Panel",
  "nav.goToAdmin": "Go to Admin",
  "nav.admin": "Admin",

  // === Auth ===
  "auth.login": "Login",
  "auth.register": "Sign Up",
  "auth.logout": "Logout",
  "auth.credits": "Credits",
  "auth.loginTitle": "Sign In",
  "auth.password": "Password",
  "auth.name": "Name",
  "auth.orLoginWith": "Or sign in with",
  "auth.noAccount": "Don't have an account?",
  "auth.registerLink": "Sign Up",
  "auth.hasAccount": "Already have an account?",
  "auth.loginLink": "Sign In",
  "auth.registerSuccess": "Registration successful! Check your email.",
  "auth.invalidToken": "Invalid authorization token",
  "auth.loading": "Loading...",

  // === Verify ===
  "verify.title": "Email Verification",
  "verify.checking": "Verifying token...",
  "verify.tokenNotFound": "Verification token not found.",
  "verify.success": "Email verified successfully!",
  "verify.backToLogin": "Back to login page",

  // === Home Page ===
  "home.heroTitle1": "IMAGINATION",
  "home.heroTitle2": "BEYOND REALITY",
  "home.heroDescription":
    "The ultimate AI studio. Combine models, use professional prompts and create perfect images.",
  "home.startGenerating": "Start Generating",
  "home.goToMarketplace": "Go to Marketplace",

  // === Generator Page ===
  "gen.sourcePhoto": "Source Photo (Optional)",
  "gen.remove": "Remove",
  "gen.dropzone": "Drag & drop a photo here or click to browse",
  "gen.dropzoneFormats": "Supported formats: JPG, PNG",
  "gen.promptTitle": "Prompt (Description)",
  "gen.promptPlaceholder":
    "A futuristic cyberpunk city at night, neon lights reflecting in puddles...",
  "gen.modelTitle": "Model & Settings",
  "gen.aspectRatio": "Aspect Ratio",
  "gen.resolution": "Resolution (Quality)",
  "gen.generating": "Generating...",
  "gen.createButton": "Create",
  "gen.creditsUnit": "Credits",
  "gen.sendingPrompt": "Sending prompt...",
  "gen.inQueue": "In queue...",
  "gen.generatingStatus": "Generating...",
  "gen.timeoutError": "Generation timed out. Please try again later.",
  "gen.failedError": "Generation failed!",
  "gen.creditsError": "Not enough credits for generation!",
  "gen.requestError": "Error sending generation request",
  "gen.waitingPrompt": "Waiting for your prompt...",
  "gen.galleryTitle": "My Generations (Google Drive)",
  "gen.galleryEmpty": "History is empty. Create your first image!",

  // === Marketplace ===
  "market.title": "AI Templates Marketplace",
  "market.description":
    "Discover thousands of ready-made AI prompts created by top authors.",
  "market.all": "All",
  "market.free": "Free",
  "market.premium": "Premium",

  // === Gallery ===
  "gallery.title": "Community Gallery",
  "gallery.description": "See what other users are creating right now.",
  "gallery.popular": "Popular",
  "gallery.new": "New",
  "gallery.best": "Best",
  "gallery.remix": "Remix",

  // === Templates ===
  "templates.title": "Prompt Templates",
  "templates.description": "Start creating with perfectly crafted prompts.",
  "templates.all": "All",
  "templates.emptyCategory": "No templates in this category yet.",

  // === My Generations ===
  "myGen.title": "My Generations",
  "myGen.description": "All your generated images",
  "myGen.refresh": "Refresh",
  "myGen.loginRequired": "Login Required",
  "myGen.loginDescription": "Sign in to view your generation history.",
  "myGen.empty": "No Generations Yet",
  "myGen.emptyDescription":
    "You haven't created any images yet. Go to the Generator and create your first one!",
  "myGen.goToGenerator": "Go to Generator",
  "myGen.savedToDrive": "Saved to Google Drive!",
  "myGen.driveNotConnected":
    "Google Drive not connected. Link it in Cloud Storage settings.",
  "myGen.saveError": "Error saving to Google Drive",
  "myGen.alreadySaved": "Already saved",
  "myGen.saveToDrive": "Save to Google Drive",
  "myGen.template": "Template",
  "myGen.shareText": "Check out this generation from Arrena Photo!",
  "myGen.shareTitle": "Arrena Generation",
  "myGen.shareFailed": "Failed to share",
  "myGen.downloadTooltip": "Download",
  "myGen.shareTooltip": "Share",
  "myGen.closeTooltip": "Close",
  "myGen.aiModel": "AI Model",

  // === My Templates ===
  "myTemplates.title": "My Templates",
  "myTemplates.description": "Manage templates you have created.",
  "myTemplates.empty": "You have no templates yet.",
  "myTemplates.createButton": "Create Template",

  // === AI Providers ===
  "ai.title": "AI Providers",
  "ai.description":
    "Connect your API keys or local instances to generate without spending platform credits.",
  "ai.connected": "Connected",
  "ai.disconnected": "Disconnected",
  "ai.connect": "Connect",
  "ai.disconnect": "Disconnect",

  // === Cloud Storage ===
  "cloud.title": "Cloud Storage",
  "cloud.description":
    "Connect storage to automatically save generated images.",
  "cloud.googleDriveTitle": "Google Drive",
  "cloud.googleDriveDesc":
    "Link your Google Drive account to save generated images directly to your cloud with one click.",
  "cloud.googleDriveConnect": "Connect Google Drive",
  "cloud.googleDriveDisconnect": "Disconnect",
  "cloud.s3Title": "AWS S3 / Cloudflare R2 / MinIO",
  "cloud.bucketName": "Bucket Name",
  "cloud.accessKey": "Access Key ID",
  "cloud.secretKey": "Secret Access Key",
  "cloud.testConnection": "Test Connection",
  "cloud.save": "Save",

  // === My Templates (Legacy/Alternative Keys) ===
  "myTpl.title": "My Templates",
  "myTpl.description": "Manage your created prompts and templates.",
  "myTpl.create": "+ Create",
  "myTpl.empty": "No Templates Yet",
  "myTpl.emptyDescription":
    "You haven't created any templates yet. Package your best prompts into a template and share or sell them on the marketplace.",
  "myTpl.goToGenerator": "Go to Generator",

  // === Profile ===
  "profile.personal": "Personal Information",
  "profile.security": "Security & Access",
  "profile.appearance": "Appearance",
  "profile.billing": "Billing & Plans",
  "profile.notifications": "Notifications",
  "profile.statistics": "Statistics",
  "profile.activity": "Activity History",

  // === Billing ===
  "billing.title": "Billing & Plans",
  "billing.description": "Manage your plan, credits and payment methods.",
  "billing.overview": "Overview",
  "billing.plans": "Plans & Credits",
  "billing.usage": "AI Usage",
  "billing.payment": "Payment Settings",
  "billing.lowCreditsTitle": "Less than 20% credits remaining",
  "billing.lowCreditsDescription":
    "We recommend topping up your balance or upgrading your plan to avoid interruptions.",
  "billing.topUp": "Top Up",

  // === Profile/Billing Overview ===
  "billing.overview.active": "Active",
  "billing.overview.free": "Free",
  "billing.overview.activeUntil": "Subscription active until",
  "billing.overview.perMonth": "/ mo",
  "billing.overview.creditsLeft": "Credits Left",
  "billing.overview.outOf": "out of",
  "billing.overview.usedPeriod": "Used in period",
  "billing.overview.creditsWord": "credits",
  "billing.overview.features": "Available plan features:",
  "billing.overview.manage": "Manage Subscription",
  "billing.overview.manageDesc":
    "Change your plan, update payment method, or cancel your subscription.",
  "billing.overview.changePlan": "Change Plan",
  "billing.overview.cancelPlan": "Cancel",
  "billing.overview.stats": "Monthly Statistics",
  "billing.overview.usedCredits": "Credits used",
  "billing.overview.imagesGenerated": "Images generated",
  "billing.overview.viewStats": "View detailed statistics в†’",
  "billing.overview.cancelModalTitle": "Cancel Subscription",
  "billing.overview.cancelModalDesc1": "You are canceling the",
  "billing.overview.cancelModalDesc2":
    "subscription. Note: no refunds are issued for the remaining period.",
  "billing.overview.yesCancel": "Yes, cancel subscription",
  "billing.overview.noCancel": "I changed my mind",

  // === Profile/Billing Plans ===
  "billing.plans.title": "Available Plans",
  "billing.plans.yourPlan": "Your Plan",
  "billing.plans.perMonth": "/ mo",
  "billing.plans.credits": "credits",
  "billing.plans.currentPlan": "Current Plan",
  "billing.plans.buyCredits": "One-time Credits Top Up",
  "billing.plans.buyCreditsDesc":
    "Purchased credits do not expire and are used first.",
  "billing.plans.promoTitle": "Activate Promo Code",
  "billing.plans.promoDesc":
    "If you have a gift code or discount coupon, enter it here.",
  "billing.plans.apply": "Apply",
  "billing.plans.promoError": "Invalid or expired promo code.",
  "billing.plans.promoApplied": "Promo code applied!",
  "billing.plans.promoDiscount": "20% discount applied!",
  "billing.plans.promoNext": "Will be applied to your next billing.",
  "billing.plans.free100": "You received 100 credits!",
  "billing.plans.upgradeSuccess": "Plan successfully changed!",
  "billing.plans.updateFailed": "Failed to update subscription on server",
  "billing.plans.downgradeButton": "Downgrade",
  "billing.plans.upgradeButton": "Upgrade",
  "billing.plans.paymentError": "Payment error",
  "billing.plans.creditsSuccess": "Credits successfully added!",

  // === Profile/Billing Usage ===
  "billing.usage.title": "AI Usage",
  "billing.usage.desc":
    "Detailed breakdown of credit usage for the current month",
  "billing.usage.totalSpent": "Total Spent",
  "billing.usage.imageGen": "Image Generation",
  "billing.usage.templates": "Template Usage",
  "billing.usage.api": "API Calls",
  "billing.usage.chartTitle": "Credit Usage",

  // === Profile/Billing Payment ===
  "billing.payment.title": "Payment Methods",
  "billing.payment.desc": "Add a card for automatic subscription renewal.",
  "billing.payment.addCard": "+ Add Card",
  "billing.payment.defaultCard": "Default",
  "billing.payment.makeDefault": "Make Default",
  "billing.payment.delete": "Delete",
  "billing.payment.billingHistory": "Billing History",
  "billing.payment.date": "Date",
  "billing.payment.amount": "Amount",
  "billing.payment.status": "Status",
  "billing.payment.invoice": "Invoice",
  "billing.payment.statusSuccess": "Paid",
  "billing.payment.statusFailed": "Failed",
  "billing.payment.download": "Download",

  // === Profile Pages ===
  "profile.personal.title": "Personal Information",
  "profile.personal.desc": "Update your name and contact details.",
  "profile.personal.avatar": "Profile Avatar",
  "profile.personal.upload": "Upload",
  "profile.personal.remove": "Remove",
  "profile.personal.name": "Full Name",
  "profile.personal.firstName": "First Name",
  "profile.personal.lastName": "Last Name",
  "profile.personal.nickname": "Nickname",
  "profile.personal.bio": "Bio",
  "profile.personal.socialLinks": "Social Links",
  "profile.personal.telegram": "Telegram",
  "profile.personal.instagram": "Instagram",
  "profile.personal.website": "Website",
  "profile.personal.email": "Email Address",
  "profile.personal.save": "Save Changes",

  "profile.security.title": "Security",
  "profile.security.desc": "Manage passwords and secure your account.",
  "profile.security.changePassword": "Change Password",
  "profile.security.currentPassword": "Current Password",
  "profile.security.newPassword": "New Password",
  "profile.security.confirmPassword": "Confirm New Password",
  "profile.security.sessions": "Active Sessions",
  "profile.security.terminate": "Terminate",
  "profile.security.current": "Current",

  "profile.appearance.title": "Appearance",
  "profile.appearance.desc": "Customize the app interface.",
  "profile.appearance.theme": "Theme",
  "profile.appearance.dark": "Dark",
  "profile.appearance.light": "Light",
  "profile.appearance.system": "System",
  "profile.appearance.accent": "Accent Color",
  "profile.appearance.fontSize": "Font Size",
  "profile.appearance.fontSizeDesc": "Adjust the interface text size.",
  "profile.appearance.compactMode": "Compact Mode",
  "profile.appearance.compactModeDesc":
    "Decrease spacing to fit more content on screen.",
  "profile.appearance.animations": "Interface Animations",
  "profile.appearance.animationsDesc":
    "Enable smooth transitions and micro-interactions.",
  "profile.appearance.save": "Save Preferences",

  "profile.notifications.title": "Notifications",
  "profile.notifications.desc": "Manage email and push notifications.",
  "profile.notifications.email": "Email Notifications",
  "profile.notifications.push": "Push Notifications",
  "profile.notifications.updates": "Updates & News",
  "profile.notifications.billing": "Billing & Subscriptions",

  "profile.statistics.title": "Statistics",
  "profile.statistics.desc": "Analytics for your AI usage.",

  "profile.activity.title": "Activity History",
  "profile.activity.desc": "Log of actions in your account.",
  "ui.confirmDelete.title": "Confirm Deletion",
  "ui.confirmDelete.description":
    "This action cannot be undone. Are you sure you want to delete",
  "ui.confirmDelete.itemName": "this item",
  "ui.confirmDelete.cancel": "Cancel",
  "ui.confirmDelete.confirm": "Delete",
  "ui.confirmDelete.deleting": "Deleting...",
  "ui.swipeHint.right.title": "Swipe Right",
  "ui.swipeHint.right.desc": "Opens the main application menu",
  "ui.swipeHint.left.title": "Swipe Left",
  "ui.swipeHint.left.desc": "Closes the menu and returns to content",
  "ui.swipeHint.down.title": "Swipe Down",
  "ui.swipeHint.down.desc": "Refreshes the page from the top",
  "ui.swipeHint.twoFingers.title": "Two-Finger Swipe",
  "ui.swipeHint.twoFingers.desc": "Quickly switch between pages (up/down)",
  "ui.swipeHint.skip": "Skip",
  "ui.swipeHint.next": "Next",
  "ui.swipeHint.gotIt": "Got It!",

  "admin.monitor.success": "Monitoring settings saved",
  "admin.monitor.error": "Error saving settings",
  "admin.monitor.title": "Auto-monitor",
  "admin.monitor.enable": "Enable Auto-check",
  "admin.monitor.desc": "Regularly check API availability and balance",
  "admin.monitor.interval": "Check interval",
  "admin.monitor.intervals.realtime": "Real-time (every 10 sec)",
  "admin.monitor.intervals.1m": "Every minute",
  "admin.monitor.intervals.5m": "Every 5 minutes",
  "admin.monitor.intervals.10m": "Every 10 minutes",
  "admin.monitor.intervals.30m": "Every 30 minutes",
  "admin.monitor.intervals.1h": "Every hour",
  "admin.monitor.saving": "Saving...",
  "admin.monitor.save": "Save",
  "admin.templates.errorLoad": "Error loading templates",
  "admin.templates.successSave": "Model successfully assigned to templates",
  "admin.templates.errorSave": "Error saving",
  "admin.templates.title": "Template Assignment",
  "admin.templates.model": "Model",
  "admin.templates.searchPlaceholder": "Search by template name or category...",
  "admin.templates.deselectAll": "Deselect All",
  "admin.templates.selectAll": "Select All",
  "admin.templates.loading": "Loading templates...",
  "admin.templates.notFound": "No templates found",
  "admin.templates.category": "Category",
  "admin.templates.noCategory": "Uncategorized",
  "admin.templates.selected": "Selected",
  "admin.templates.of": "of",
  "admin.templates.saveLinks": "Save Assignments",
  "admin.topbar.feedback": "Feedback",
  "admin.topbar.docs": "Docs",
  "admin.topbar.logout": "Logout",
  "admin.sidebar.billing.title": "Subscriptions & Billing",
  "admin.sidebar.billing.tariffs": "Plans & Limits",
  "admin.sidebar.billing.history": "Payment History",
  "admin.sidebar.billing.promocodes": "Promo Codes",
  "admin.sidebar.backToHome": "Back to Home",

  "billing.plans.downgrade.title": "Attention",
  "billing.plans.downgrade.desc":
    "You are downgrading to the free plan. Note: no refunds are issued for the remaining period.",
  "billing.payment.expired": "Expired",
  "billing.payment.limit": "Limit",
  "billing.payment.balance": "Balance",
  "billing.payment.addCardTitle": "Add Card",
  "billing.payment.cardNumber": "Card Number",
  "billing.payment.expiryDate": "Expiry Date (MM/YY)",
  "billing.payment.cvv": "CVV",
  "billing.payment.maxLimit": "Max Limit ($)",
  "billing.payment.cardBalance": "Card Balance ($)",
  "billing.payment.save": "Save",
  "billing.payment.editMaxLimit": "Edit Max Limit",
  "billing.payment.saveLimit": "Save Limit",
  "billing.payment.rowsPerPage": "Rows per page:",
  "billing.payment.pageOf": "Page {current} of {total}",
  "billing.payment.previous": "Previous",
  "billing.payment.next": "Next",

  "billing.plans.features.free.1": "Up to 1 task",
  "billing.plans.features.free.2": "Standard speed",
  "billing.plans.features.free.3": "Watermark",
  "billing.plans.features.starter.1": "Up to 2 tasks",
  "billing.plans.features.starter.2": "Standard speed",
  "billing.plans.features.starter.3": "No watermark",
  "billing.plans.features.pro.1": "Up to 5 tasks",
  "billing.plans.features.pro.2": "High speed",
  "billing.plans.features.pro.3": "Commercial license",
  "billing.plans.features.business.1": "Up to 20 tasks",
  "billing.plans.features.business.2": "Max speed",
  "billing.plans.features.business.3": "API access",

  "profile.appearance.skinTitle": "Website Skin (Style)",
  "profile.appearance.skinLuxury": "Luxury Gold",
  "profile.appearance.skinNeon": "Neon Cyberpunk",
  "profile.appearance.skinDesc": "Choose the overall interface styling.",
  "profile.appearance.skinLuxuryDesc":
    "Premium dark interface with metallic accents.",
  "profile.appearance.skinNeonDesc":
    "Vibrant style with neon glows and bright accent color.",
  "profile.appearance.skinPremium": "Premium Editions",
  "profile.appearance.skinPremiumDesc":
    "High-tech premium interface with frosted glass effects and 3D components.",

  "generate.cancelError": "Generation cancelled. Credits are not refunded.",
  "generate.clearPrompt": "Clear prompt",
  "generate.hiddenPrompt": "Prompt is hidden on free plan",
  "generate.goToPlans": "Go to plans",
  "generate.cancelGeneration": "Cancel generation",
  "generate.warning": "Warning",
  "generate.cancelConfirmText":
    "Are you sure you want to cancel the generation? Deducted credits will not be refunded.",
  "generate.continue": "Continue",
  "generate.yesCancel": "Yes, cancel",

  "billing.overview.date": "July 21, 2026",
  "templates.perPage": "per page",
  "common.prev": "Prev",
  "common.next": "Next",

  // === Payment Modal ===
  "payment.modal.buyCredits": "Buy Credits",
  "payment.modal.upgradePlan": "Upgrade Plan",
  "payment.modal.creditsDesc":
    "Select a credit package to continue your generations.",
  "payment.modal.upgradeDesc":
    "Upgrade to {plan} for more features and credits.",
  "payment.modal.popular": "Popular",
  "payment.modal.credits": "credits",
  "payment.modal.orPayWithCard": "Or pay with card",
  "payment.modal.payNow": "Pay Now",
  "payment.modal.securePayment": "Secure payment via",
  "payment.modal.success": "Payment Successful!",
  "payment.modal.creditsAdded": "Credits have been added to your account.",
  "payment.modal.subActive": "Your subscription is now active!",
  "payment.modal.initFailed": "Failed to initialize payment",
  "payment.modal.initLoading": "Preparing payment...",
  "payment.modal.genericError": "An error occurred. Please try again.",

  // === Checkout & Legal ===
  "checkout.termsAgree":
    "I have read and agree to the Terms of Service, Privacy Policy, and Billing & Refund Policy.",
  "checkout.subAgree":
    "I understand that my subscription will automatically renew until cancelled. The subscription cost will be automatically charged to my payment method according to the selected plan.",
  "checkout.disclaimerTitle": 'By clicking "Pay", you confirm that:',
  "checkout.disclaimer1": "the provided card details are valid;",
  "checkout.disclaimer2":
    "you authorize HSHA Sandbox to charge the current payment amount;",
  "checkout.disclaimer3":
    "if a subscription plan is selected, you authorize automatic charges for subsequent periods until the subscription is cancelled;",
  "checkout.disclaimer4":
    "you have read and agree to the Terms of Service, Privacy Policy, and Billing & Refund Policy.",
  "checkout.legal.terms": "Terms of Service",
  "checkout.legal.privacy": "Privacy Policy",
  "checkout.legal.billing": "Billing Policy",
  "checkout.legal.refund": "Refund Policy",

  "legal.terms.title": "Terms of Service",
  "legal.terms.content":
    "1. General Provisions\n\n2. Account Registration\n\n3. Subscriptions\n\n4. Payment\n\n5. Automatic Renewal\nAll subscriptions automatically renew for the next billing period.\nRenewal is automatic using the payment method provided by the user.\nThe user may cancel the subscription at any time via account settings.\nUpon cancellation, automatic renewal stops, but the paid period remains active until it ends.\n\n6. Cancellation\n\n7. Refunds\n\n8. Liability\n\n9. Limitation of Liability\n\n10. Price Changes\n\n11. Termination\n\n12. Contact Information",

  "legal.privacy.title": "Privacy Policy",
  "legal.privacy.content":
    "HSHA Sandbox collects data to provide services.\n\nHSHA Sandbox does not store full credit card numbers.\nPayment processing is handled by a certified payment provider.\n\nContact...",

  "legal.billing.title": "Billing Policy",
  "legal.billing.content":
    "Payment is made using bank cards and supported payment services.\n\nBy subscribing, the user authorizes the automatic charging of the selected plan's cost until the subscription is cancelled.\n\nFunds are charged on the subscription renewal date.\n\nThe cost is displayed before confirming payment.\n\nAfter subscribing, HSHA Sandbox automatically charges the cost of each subsequent billing period.\nIf a charge fails, the system may retry several times.\nUpon prolonged failure to pay, access to the subscription may be restricted.",

  "legal.refund.title": "Refund Policy",
  "legal.refund.content":
    "Unless otherwise required by law, paid subscriptions are non-refundable once the digital service has begun.\n\nRefunds are possible in cases of:\nвЂў double billing;\nвЂў technical errors;\nвЂў accidental payments;\nвЂў other cases provided by law.\n\nNon-refundable:\nвЂў used credits;\nвЂў completed generations;\nвЂў active subscriptions after service provision has started (unless law provides otherwise).",
};

export default en;
